### PR TITLE
H-Blank effect routine moved to assembly

### PR DESCRIPTION
**Pull request by JoaoBaptMG**
I tested it on the mode-7 example and debugged it using No$GBA. It works properly on that example, but I am not that sure on the other examples.

### CODE REVIEW

**Comment by GValiente** [comment]
It looks great! However it seems there's an issue with the first screen line.

It shows in the world map example:

C++:
world_map-1

ASM:
world_map-0

**Comment by GValiente** [comment]
Replacing `mvnhi r0, #1` with `subgt r0, r0, #227` seems to fix it, but I don't know ASM xD

**Comment by JoaoBaptMG** [comment]
I think I just fixed it. I had forgotten that `mvn` actually moves the *binary NOT* version of the constant field instead of the 2-complement negated form of it. So `mvnhi r0, #1` actually moved -2 into `r0`, which caused the routine to read `entries[-1]` in this case. I fixed by replacing it by `mvnhi r0, #0`.

**Comment by GValiente** [comment]
Hm, it keeps failing for me.

I think I have fixed it, but could you please check it out?

```
    @ this implement if (vcount < 159) vcount++; else if (vcount > 226) vcount = 0; else return;
    @ cmp     r0, #226                @ if it's > 226, set it to -1
    @ mvnhi   r0, #0                  @ now vcount = -1 or original vcount
    @ subgt   r0, r0, #227
    @ add     r0, r0, #1              @ add 1 to it (r0 = vcount+1 or 0)
    @ cmp     r0, #160                @ if vcount + 1 >= 160
    @ bxhs    lr                      @ bail out
    @ mov     r0, r0, lsl #1          @ now r0 = vcount*2

    cmp     r0, #158
    addls   r0, r0, #1              @ if (vcount <= 158) ++vcount;
    bls     .loadEntries            @ if (vcount > 158) goto loadEntries;
    cmp     r0, #226
    bxls    lr                      @ if (vcount <= 226) return;
    mov     r0, #0                  @ if (vcount > 226) vcount = 0;

.loadEntries:
    mov     r0, r0, lsl #1          @ now r0 = vcount*2
```

**Comment by JoaoBaptMG** [comment]
Strange... the image I get on mGBA is actually the same as the C++ version when I replace `mvnhi r0, #1` for `mvnhi r0, #0`.

world_map-0

**Comment by JoaoBaptMG** [comment]
I also added a final commit that replaces the obscure `mvn` instruction by the much more expressive `movhi r0, #-1`, which the assembler is actually able to translate to the actual `mvn` instruction. Kudos for code clarity!

**Comment by JoaoBaptMG** [comment]
> 
> 
> Hm, it keeps failing for me.
> 
> I think I have fixed it, but could you please check it out?
> 
> ```
>     @ this implement if (vcount < 159) vcount++; else if (vcount > 226) vcount = 0; else return;
>     @ cmp     r0, #226                @ if it's > 226, set it to -1
>     @ mvnhi   r0, #0                  @ now vcount = -1 or original vcount
>     @ subgt   r0, r0, #227
>     @ add     r0, r0, #1              @ add 1 to it (r0 = vcount+1 or 0)
>     @ cmp     r0, #160                @ if vcount + 1 >= 160
>     @ bxhs    lr                      @ bail out
>     @ mov     r0, r0, lsl #1          @ now r0 = vcount*2
> 
>     cmp     r0, #158
>     addls   r0, r0, #1              @ if (vcount <= 158) ++vcount;
>     bls     .loadEntries            @ if (vcount > 158) goto loadEntries;
>     cmp     r0, #226
>     bxls    lr                      @ if (vcount <= 226) return;
>     mov     r0, #0                  @ if (vcount > 226) vcount = 0;
> 
> .loadEntries:
>     mov     r0, r0, lsl #1          @ now r0 = vcount*2
> ```

FInally, while this solution is correct (and actually resembles the code a lot more than mine), it uses 6 instructions and a possible branch (possibly consuming 6 or 7 cycles, I need to do the math correctly), while mine uses only 5. Given that this is a h-blank routine, it means 228 cycles saved per frame.

**Pull request merged**
