### PR TITLE
random set seed

### PR DESCRIPTION
**Pull request by ggraciadev**
I've added a little simple function to set a seed to the random generation number. I think it works pretty good.

### CODE REVIEW

**Comment by GValiente** [comment]
How can you be sure that calling that method is not going to break the random number generator?

**Comment by GValiente** [comment]
Closed due to lack of activity.

**Comment by ggraciadev** [comment]
Oh, i didn't see that email, sorry.
I'm working on a Roguelike game for my Uni Thesis and i'm using this system
and is working pretty fine for me. Also, my Thesis director sayed to me
that this is a rly simple way to do it and it will work. The numbers x, y
and z are random numbers and ni matters what number they are. And i'm only
changing one.

In addition to this, i'm creating an engine layer like Unreal/Unity. If you
want i can share you my repo to have a look.

Btw, i think we can talk in spanish, Gabriel Valiente and Butano says to me
that you be Spanish or Latin American, so the next emails could be in
spanish if you want  i'm from Barcelona '^^

Thank you.

**Comment by GValiente** [comment]
Of course random seed initial values (x, y and z) matter a lot for output quality.
For example, if x, y and z are set to zero, output random values are always going to be zero.

bn::random is a [Marsaglia xorshift generator](http://www.jstatsoft.org/v08/i14/paper), you can read about it in the link.

But as always, if what you're doing works for you, you always can use your own random generator instead of using bn::random.

Yeah, I'm from Spain (it's Gustavo, not Gabriel xD).
If you want to share your work and talk about Butano stuff, the [gbadev forums](https://forum.gbadev.net/) and the [gbadev Discord server](https://discord.io/gbadev) are great for that.

**Comment by ggraciadev** [comment]
Oh perdon, tuve un profe en la uni que se llamaba Gabriel Valiente y mi
cabeza le ha pegado un chispazo esta mañana '^^. Lo que he añadido de la
seed, almenos con numeros pequeños me sirve muy bien y me da habitaciones
bastante diferentes entre sí, estoy satisfecho con el resultado. Cuando
acabe el TFG seguramente lo comparta.
Por cierto, muy buen motor y muy sencillo de usar. Como he dicho, le he
añadido una capa por encima con cosas tipo GameObject con jerarquia entre
objetos (attachements) y GameObjectsComponents. Está quedando bastante
chulo, la verdad.

Saludos

**Pull request closed without merging**
