### PR TITLE
Add camera pitch on mode 7

### PR DESCRIPTION
**Pull request by ultrasuperpingu**
Of course based on the tonc example (https://www.coranac.com/tonc/text/mode7ex.htm).

I implemented a version with backdrop display too but it's clearly an ugly hack.

On the tonc implementation, he change the background configuration on hblank when currentLine == horz with:

```
BFN_SET(REG_DISPCNT, DCNT_MODE1, DCNT_MODE);
REG_BG2CNT= m7_level.bgcnt_floor;
```

but as far as I understand, it's not possible with butano. I wanted to show/hide the background/floor on hblank but I didn't find a way to do it with butano. And he says:

> Switching between the backdrop and floor backgrounds is actually trickier than it sounds. You could, for example, have a separate background for each and enable/disable them depending on your needs. The problem is that it seems to take about 3 scanlines before a background is fully set up in hardware, so you'll see crap during that time. In other words, this solution is no good.

If you have hints from me to complete backdrop management, I'll be happy to add this :)

### CODE REVIEW

**Comment by ultrasuperpingu** [comment]
Using a window seems good. I haven't thought about it :)
It make the using of windows for other purpose impossible though.
Maybe I'm wrong but using sprites (multiples because one would be too small) seems a bit complicated both in code and asset creation...

There is really no way to do a `set_visible` on HBlank with butano? I'd like try try to see what happens.

Thanks for the answer :)

**Comment by GValiente** [comment]
GBA offers two rect windows and sprites can be used as another window.

You only need one rect window for hiding the backdrop or the ground at the horizon scanline, so there's more than enough for a "mode 7" background and some other effects.

**Comment by ultrasuperpingu** [comment]
Ok, I'll try to implement it with window but is there really no way to do a set_visible on HBlank with butano?

**Comment by GValiente** [comment]
No.

**Comment by GValiente** [comment]
Sorry, but I thought this was an issue instead of a pull request.

Currently I'm not interested in reworking this example, since it is only a quick port of the [first "mode 7" Tonc chapter](https://www.coranac.com/tonc/text/mode7.htm).

A *proper* "mode 7" background implementation would require much more code, and even the way the "mode 7" background is implemented in the second Tonc chapter is not the optimal way, so I prefer maintaining the example as it is to reduce the required code to display the effect.

**Comment by ultrasuperpingu** [comment]
I know the "mode 7" example is only a quick port of the [first "mode 7" Tonc chapter](https://www.coranac.com/tonc/text/mode7.htm).

That's why I thought it could be useful to provide a quick port to the [second "mode 7" Tonc chapter](https://www.coranac.com/tonc/text/mode7ex.htm) in the same example.

I thought it could be a good start for somebody trying to implement a real "mode 7" thing :)

But I understand your point :)

**Comment by ultrasuperpingu** [comment]
Just to know, what's wrong with the code I provided. I know it's far from perfect, (again, the idea was to provide a quick port of a part of the second "mode 7" Tonc chapter), but it's pretty much working. Maybe I can fix the things you don't like?
And because it's just an example, I don't think you really have to provide support of it.

**Comment by GValiente** [comment]
Of course I have to maintain and provide support for the examples, since most people usually start building their games from them.

**Pull request closed without merging**
